version: 2.1

orbs:
  go: circleci/go@1.5.0
  node: circleci/node@4.1.0

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/test:
          verbose: true
          failfast: true
      - run: go build -o bin/goceps1 .
      - run: go build -o bin/goceps2 .
      - run:
          name: Creating artifact
          command: |
            mkdir /tmp/artifact-1;
            cp bin/* /tmp/artifact-1
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

  release:
    install-node-example:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run:
          name: Get artifact
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/lucasmdomingues/goceps/latest/artifacts | grep -o 'https://[^"]*' > artifact.txt
      - run: 
          name: Download artifact
          command: <artifact.txt xargs -P4 -I % wget % $CIRCLE_TOKEN -P bin
      - run: ls bin

workflows:
  build_and_test:
    jobs:
      - build_and_test
      - release:
          requires:
            - build_and_test
