version: 2.1

orbs:
  go: circleci/go@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - run: node --version
      - go/test:
          verbose: true
          failfast: true
      - run: go build -o bin/goceps .

workflows:
  build_and_test:
    jobs:
      - build_and_test
