version: 2.1

orbs:
  go: circleci/go@1.5.0

jobs:
  build:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - run: go build -o bin/covid-api .

workflows:
  main:
    jobs:
      - build
