version: 2

jobs:
  build:
    docker:
      - image: golang:1.14-alpine
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v ./...
      - run: go build
