version: 2.1

orbs:
  go: circleci/go@1.5.0
  node: circleci/node@4.1.0

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/test:
          verbose: true
          failfast: true
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
  release:
    install-node-example:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run:
          name: Get build
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/lucasmdomingues/goceps/latest/artifacts | grep -o 'https://[^"]*' > artifacts.txt
      - run: ls

workflows:
  build_and_test:
    jobs:
      - build_and_test
      - release:
          requires:
            - build_and_test
