version: 2.1

orbs:
  go: circleci/go@1.5.0

jobs:
  build:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - run: go build
      
workflows:
  main:
    jobs:
      - build
