version: 2.1

orbs:
  go: circleci/go@1.5.0
  node: circleci/node@4.1.0

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      - go/test:
          verbose: true
          failfast: true
      - run: mkdir -p /tmp/build;
      - run: go build -o bin/goceps .
      - run: cp /bin/* /tmp/build
      - store_artifacts:
          path: /tmp/build
  release:
    executor:
      name: node/default
      tag: "13"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          name: Get build
          command: curl -H 'Circle-Token: 609ccef46645aa23ec36c2e5744b7df92e45266d' https://circleci.com/api/v1.1/project/github/lucasmdomingues/goceps/latest/artifacts
      - run: ls

workflows:
  build_and_test:
    jobs:
      - build_and_test
      - release
